version: "3"

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: pg
    ports:
      - 5434:5432
    networks:
      - laravel

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
    ports:
      - "12001:9000"
      - "12002:9001"
    networks:
      - laravel

  npm:
    image: node:alpine
    container_name: npm
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
    networks:
      - laravel
