name: Deploy Laravel Application
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SECRET}}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      with:
        instance_name: 'fp-pso-instance'
        zone: 'asia-southeast2-a'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        command: |
            cd yaqueen
            sudo git pull --rebase
            sudo docker compose up -d