name: pull server
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: |
          cd src
          composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cd src
          cp .env.example .env
          php artisan key:generate


  pullserver:
    name: Pull Server
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 34.128.80.167
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd yacqueen
            git pull origin main
            sudo docker compose up -d --no-cache
 
